openapi: 3.0.0
info:
  title: Movie API
  version: 1.0.0
  description: A REST API to manage movie details

servers:
  - url: http://localhost:3000/api/v1
    description: Local development server

paths:
  /movies:
    get:
      summary: Get all movies
      responses:
        '200':
          description: A list of movies
    post:
      summary: Add a new movie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieInput'
      responses:
        '201':
          description: Movie added

  /movies/{id}:
    get:
      summary: Get a movie by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Movie found
        '404':
          description: Not found

    put:
      summary: Update a movie by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovieInput'
      responses:
        '200':
          description: Movie updated

    delete:
      summary: Delete a movie by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Movie deleted

components:
  schemas:
    MovieInput:
      type: object
      required:
        - title
        - director
        - year
        - rating
      properties:
        title:
          type: string
          example: Inception
        director:
          type: string
          example: Christopher Nolan
        year:
          type: integer
          example: 2010
        rating:
          type: number
          format: float
          example: 8.8
